---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com | sh
          docker compose version
      - name: Test
        run:  docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run:  docker-compose run --rm app sh -c "flake8"